### ISSUE TITLE
Use Gurobi

### ISSUE THREAD

**Issue by jonrkarr** [biosimulations/biosimulations-bigg#3]
- [x] Add optional `gurobi` requirement which requires `biosimulators_cobra[gurobi]`
- [x] Add installation of this requirement to GitHub action
- [x] Map Gurobi secrets to environment variables in GitHub action:
   ```yaml
    env:
        GRB_WLSACCESSID: ${{ secrets.GRB_WLSACCESSID }}
        GRB_WLSSECRET: ${{ secrets.GRB_WLSSECRET }}
        GRB_LICENSEID: ${{ secrets.GRB_LICENSEID }}
    ```
